jwt:
  secret: mySuperSecretKey
  expiration: 3600000


fcm:
  value: baby24-notification-fcm.json

swagger:
  server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}

springdoc:
  swagger-ui:
    path: /swagger

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baby24?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - profile
              - email

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB